name: tipsen
on:
  schedule:
    - cron: '17 12 * * *'
    - cron: '58 1 * * *'
    - cron: '53 2 * * *'
    - cron: '42 3 * * *'
    - cron: '8 6 * * *'
    - cron: '57 8 * * *'
    
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
    - name: API req
      run: |
        curl -X GET "https://tipsen.up.railway.app/absen" -o data.json
    - name: API res
      run: cat data.json
